#############################################################################
# Makefile for building: smartScore
# Generated by qmake (2.01a) (Qt 4.8.5) on: ?? 5. ??? 16:28:02 2014
# Project:  SmartScore.pro
# Template: app
# Command: d:\C++\Qt\4.8.5\bin\qmake.exe -spec d:\C++\Qt\4.8.5\mkspecs\win32-g++ CONFIG+=release -o Makefile SmartScore.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUNICODE -DQT_DLL -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_THREAD_SUPPORT -DQT_NEEDS_QMAIN
CFLAGS        = -pipe -O2 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -O2 -frtti -fexceptions -mthreads -Wall -Wextra $(DEFINES)
INCPATH       = -I"d:\C++\Qt\4.8.5\include\QtCore" -I"d:\C++\Qt\4.8.5\include\QtGui" -I"d:\C++\Qt\4.8.5\include\QtSql" -I"d:\C++\Qt\4.8.5\include" -I"d:\C++\Qt\4.8.5\include\ActiveQt" -I"moc" -I"d:\C++\Qt\4.8.5\mkspecs\win32-g++"
LINK        =        g++
LFLAGS        =        -Wl,-s -mthreads -Wl,-subsystem,windows
LIBS        =        -L"d:\C++\Qt\4.8.5\lib" -lmingw32 -lqtmain -lQtSql4 -lQtGui4 -lQtCore4 
QMAKE         = d:\C++\Qt\4.8.5\bin\qmake.exe
IDC           = d:\C++\Qt\4.8.5\bin\idc.exe
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
COPY          = copy /y
SED           = 
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
DEL_FILE      = del
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
INSTALL_FILE    = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR     = $(COPY_DIR)

####### Output directory

OBJECTS_DIR   = obj

####### Files

SOURCES       = src\smartScoreWindow\smartScoreWindow.cpp \
		src\smartScoreWindow\centralWorkSpace.cpp \
		src\orgStruct\orgStructWidget.cpp \
		src\orgStruct\orgStructEditWidget.cpp \
		src\orgStruct\orgStructDb.cpp \
		src\orgStruct\orgStruct.cpp \
		src\orgStruct\orgStructWorkSpace.cpp \
		src\scoreCard\scoreCard.cpp \
		src\scoreCard\scoreCardWorkSpace.cpp \
		src\scoreCard\scoreCardtTeeWidget.cpp \
		src\scoreCard\scoreCardPerspectiveEditWidget.cpp \
		src\scoreCard\scoreCardDb.cpp \
		src\common\lineEdit.cpp \
		src\common\widgetLayoutInterface.cpp \
		src\common\edittLayoutInterface.cpp \
		src\common\editForm.cpp \
		src\common\editRow.cpp \
		src\test\test.cpp \
		src\main.cpp moc\moc_smartScoreWindow.cpp \
		moc\moc_centralWorkSpace.cpp \
		moc\moc_orgStructEditWidget.cpp \
		moc\moc_orgStructWidget.cpp \
		moc\moc_orgStructWorkSpace.cpp \
		moc\moc_scoreCardWorkSpace.cpp \
		moc\moc_scoreCardtTeeWidget.cpp \
		moc\moc_scoreCardPerspectiveEditWidget.cpp \
		moc\moc_lineEdit.cpp \
		moc\moc_edittLayoutInterface.cpp \
		moc\moc_editForm.cpp \
		qrc_images.cpp
OBJECTS       = obj/smartScoreWindow.o \
		obj/centralWorkSpace.o \
		obj/orgStructWidget.o \
		obj/orgStructEditWidget.o \
		obj/orgStructDb.o \
		obj/orgStruct.o \
		obj/orgStructWorkSpace.o \
		obj/scoreCard.o \
		obj/scoreCardWorkSpace.o \
		obj/scoreCardtTeeWidget.o \
		obj/scoreCardPerspectiveEditWidget.o \
		obj/scoreCardDb.o \
		obj/lineEdit.o \
		obj/widgetLayoutInterface.o \
		obj/edittLayoutInterface.o \
		obj/editForm.o \
		obj/editRow.o \
		obj/test.o \
		obj/main.o \
		obj/moc_smartScoreWindow.o \
		obj/moc_centralWorkSpace.o \
		obj/moc_orgStructEditWidget.o \
		obj/moc_orgStructWidget.o \
		obj/moc_orgStructWorkSpace.o \
		obj/moc_scoreCardWorkSpace.o \
		obj/moc_scoreCardtTeeWidget.o \
		obj/moc_scoreCardPerspectiveEditWidget.o \
		obj/moc_lineEdit.o \
		obj/moc_edittLayoutInterface.o \
		obj/moc_editForm.o \
		obj/qrc_images.o
DIST          = 
QMAKE_TARGET  = smartScore
DESTDIR        = bin\ #avoid trailing-slash linebreak
TARGET         = smartScore.exe
DESTDIR_TARGET = bin\smartScore.exe

####### Implicit rules

.SUFFIXES: .cpp .cc .cxx .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

first: all
all: Makefile  $(DESTDIR_TARGET)

$(DESTDIR_TARGET):  $(OBJECTS) 
	$(LINK) $(LFLAGS) -o $(DESTDIR_TARGET) object_script.smartScore  $(LIBS)

Makefile: SmartScore.pro  d:/C++/Qt/4.8.5/mkspecs/win32-g++/qmake.conf d:/C++/Qt/4.8.5/mkspecs/features/device_config.prf \
		d:/C++/Qt/4.8.5/mkspecs/qconfig.pri \
		d:/C++/Qt/4.8.5/mkspecs/modules/qt_webkit_version.pri \
		d:/C++/Qt/4.8.5/mkspecs/features/qt_functions.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/qt_config.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/exclusive_builds.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/default_pre.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/win32/default_pre.prf \
		src/smartScoreWindow/smartScoreWindow.pri \
		src/orgStruct/orgStruct.pri \
		src/scoreCard/scoreCard.pri \
		src/common/common.pri \
		src/test/test.pri \
		d:/C++/Qt/4.8.5/mkspecs/features/release.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/default_post.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/win32/default_post.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/win32/rtti.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/win32/exceptions.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/win32/stl.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/shared.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/warn_on.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/qt.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/win32/thread.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/moc.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/win32/windows.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/resources.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/uic.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/yacc.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/lex.prf \
		d:/C++/Qt/4.8.5/mkspecs/features/include_source_dir.prf \
		d:/C++/Qt/4.8.5/lib/qtmain.prl
	$(QMAKE) -spec d:\C++\Qt\4.8.5\mkspecs\win32-g++ CONFIG+=release -o Makefile SmartScore.pro
d:\C++\Qt\4.8.5\mkspecs\features\device_config.prf:
d:\C++\Qt\4.8.5\mkspecs\qconfig.pri:
d:\C++\Qt\4.8.5\mkspecs\modules\qt_webkit_version.pri:
d:\C++\Qt\4.8.5\mkspecs\features\qt_functions.prf:
d:\C++\Qt\4.8.5\mkspecs\features\qt_config.prf:
d:\C++\Qt\4.8.5\mkspecs\features\exclusive_builds.prf:
d:\C++\Qt\4.8.5\mkspecs\features\default_pre.prf:
d:\C++\Qt\4.8.5\mkspecs\features\win32\default_pre.prf:
src\smartScoreWindow\smartScoreWindow.pri:
src\orgStruct\orgStruct.pri:
src\scoreCard\scoreCard.pri:
src\common\common.pri:
src\test\test.pri:
d:\C++\Qt\4.8.5\mkspecs\features\release.prf:
d:\C++\Qt\4.8.5\mkspecs\features\default_post.prf:
d:\C++\Qt\4.8.5\mkspecs\features\win32\default_post.prf:
d:\C++\Qt\4.8.5\mkspecs\features\win32\rtti.prf:
d:\C++\Qt\4.8.5\mkspecs\features\win32\exceptions.prf:
d:\C++\Qt\4.8.5\mkspecs\features\win32\stl.prf:
d:\C++\Qt\4.8.5\mkspecs\features\shared.prf:
d:\C++\Qt\4.8.5\mkspecs\features\warn_on.prf:
d:\C++\Qt\4.8.5\mkspecs\features\qt.prf:
d:\C++\Qt\4.8.5\mkspecs\features\win32\thread.prf:
d:\C++\Qt\4.8.5\mkspecs\features\moc.prf:
d:\C++\Qt\4.8.5\mkspecs\features\win32\windows.prf:
d:\C++\Qt\4.8.5\mkspecs\features\resources.prf:
d:\C++\Qt\4.8.5\mkspecs\features\uic.prf:
d:\C++\Qt\4.8.5\mkspecs\features\yacc.prf:
d:\C++\Qt\4.8.5\mkspecs\features\lex.prf:
d:\C++\Qt\4.8.5\mkspecs\features\include_source_dir.prf:
d:\C++\Qt\4.8.5\lib\qtmain.prl:
qmake:  FORCE
	@$(QMAKE) -spec d:\C++\Qt\4.8.5\mkspecs\win32-g++ CONFIG+=release -o Makefile SmartScore.pro

dist:
	$(ZIP) smartScore.zip $(SOURCES) $(DIST) SmartScore.pro d:\C++\Qt\4.8.5\mkspecs\features\device_config.prf d:\C++\Qt\4.8.5\mkspecs\qconfig.pri d:\C++\Qt\4.8.5\mkspecs\modules\qt_webkit_version.pri d:\C++\Qt\4.8.5\mkspecs\features\qt_functions.prf d:\C++\Qt\4.8.5\mkspecs\features\qt_config.prf d:\C++\Qt\4.8.5\mkspecs\features\exclusive_builds.prf d:\C++\Qt\4.8.5\mkspecs\features\default_pre.prf d:\C++\Qt\4.8.5\mkspecs\features\win32\default_pre.prf src\smartScoreWindow\smartScoreWindow.pri src\orgStruct\orgStruct.pri src\scoreCard\scoreCard.pri src\common\common.pri src\test\test.pri d:\C++\Qt\4.8.5\mkspecs\features\release.prf d:\C++\Qt\4.8.5\mkspecs\features\default_post.prf d:\C++\Qt\4.8.5\mkspecs\features\win32\default_post.prf d:\C++\Qt\4.8.5\mkspecs\features\win32\rtti.prf d:\C++\Qt\4.8.5\mkspecs\features\win32\exceptions.prf d:\C++\Qt\4.8.5\mkspecs\features\win32\stl.prf d:\C++\Qt\4.8.5\mkspecs\features\shared.prf d:\C++\Qt\4.8.5\mkspecs\features\warn_on.prf d:\C++\Qt\4.8.5\mkspecs\features\qt.prf d:\C++\Qt\4.8.5\mkspecs\features\win32\thread.prf d:\C++\Qt\4.8.5\mkspecs\features\moc.prf d:\C++\Qt\4.8.5\mkspecs\features\win32\windows.prf d:\C++\Qt\4.8.5\mkspecs\features\resources.prf d:\C++\Qt\4.8.5\mkspecs\features\uic.prf d:\C++\Qt\4.8.5\mkspecs\features\yacc.prf d:\C++\Qt\4.8.5\mkspecs\features\lex.prf d:\C++\Qt\4.8.5\mkspecs\features\include_source_dir.prf d:\C++\Qt\4.8.5\lib\qtmain.prl  HEADERS RESOURCES IMAGES SOURCES OBJECTIVE_SOURCES FORMS YACCSOURCES YACCSOURCES LEXSOURCES 

clean: compiler_clean 
	-$(DEL_FILE) obj\smartScoreWindow.o obj\centralWorkSpace.o obj\orgStructWidget.o obj\orgStructEditWidget.o obj\orgStructDb.o obj\orgStruct.o obj\orgStructWorkSpace.o obj\scoreCard.o obj\scoreCardWorkSpace.o obj\scoreCardtTeeWidget.o obj\scoreCardPerspectiveEditWidget.o obj\scoreCardDb.o obj\lineEdit.o obj\widgetLayoutInterface.o obj\edittLayoutInterface.o obj\editForm.o obj\editRow.o obj\test.o obj\main.o obj\moc_smartScoreWindow.o obj\moc_centralWorkSpace.o obj\moc_orgStructEditWidget.o obj\moc_orgStructWidget.o obj\moc_orgStructWorkSpace.o obj\moc_scoreCardWorkSpace.o obj\moc_scoreCardtTeeWidget.o obj\moc_scoreCardPerspectiveEditWidget.o obj\moc_lineEdit.o obj\moc_edittLayoutInterface.o obj\moc_editForm.o obj\qrc_images.o

distclean: clean
	-$(DEL_FILE) $(DESTDIR_TARGET)
	-$(DEL_FILE) Makefile

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_smartScoreWindow.cpp moc/moc_centralWorkSpace.cpp moc/moc_orgStructEditWidget.cpp moc/moc_orgStructWidget.cpp moc/moc_orgStructWorkSpace.cpp moc/moc_scoreCardWorkSpace.cpp moc/moc_scoreCardtTeeWidget.cpp moc/moc_scoreCardPerspectiveEditWidget.cpp moc/moc_lineEdit.cpp moc/moc_edittLayoutInterface.cpp moc/moc_editForm.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_smartScoreWindow.cpp moc\moc_centralWorkSpace.cpp moc\moc_orgStructEditWidget.cpp moc\moc_orgStructWidget.cpp moc\moc_orgStructWorkSpace.cpp moc\moc_scoreCardWorkSpace.cpp moc\moc_scoreCardtTeeWidget.cpp moc\moc_scoreCardPerspectiveEditWidget.cpp moc\moc_lineEdit.cpp moc\moc_edittLayoutInterface.cpp moc\moc_editForm.cpp
moc/moc_smartScoreWindow.cpp: src/smartScoreWindow/smartScoreWindow.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\smartScoreWindow\smartScoreWindow.h -o moc\moc_smartScoreWindow.cpp

moc/moc_centralWorkSpace.cpp: src/smartScoreWindow/centralWorkSpace.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\smartScoreWindow\centralWorkSpace.h -o moc\moc_centralWorkSpace.cpp

moc/moc_orgStructEditWidget.cpp: src/orgStruct/orgStruct.h \
		src/common/comm.h \
		src/orgStruct/orgStructEditWidget.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\orgStruct\orgStructEditWidget.h -o moc\moc_orgStructEditWidget.cpp

moc/moc_orgStructWidget.cpp: src/orgStruct/orgStruct.h \
		src/common/comm.h \
		src/orgStruct/orgStructWidget.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\orgStruct\orgStructWidget.h -o moc\moc_orgStructWidget.cpp

moc/moc_orgStructWorkSpace.cpp: src/orgStruct/orgStructWorkSpace.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\orgStruct\orgStructWorkSpace.h -o moc\moc_orgStructWorkSpace.cpp

moc/moc_scoreCardWorkSpace.cpp: src/common/comm.h \
		src/scoreCard/scoreCardWorkSpace.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\scoreCard\scoreCardWorkSpace.h -o moc\moc_scoreCardWorkSpace.cpp

moc/moc_scoreCardtTeeWidget.cpp: src/common/comm.h \
		src/scoreCard/scoreCard.h \
		src/common/editRow.h \
		src/scoreCard/scoreCardtTeeWidget.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\scoreCard\scoreCardtTeeWidget.h -o moc\moc_scoreCardtTeeWidget.cpp

moc/moc_scoreCardPerspectiveEditWidget.cpp: src/common/editForm.h \
		src/common/comm.h \
		src/common/editRow.h \
		src/scoreCard/scoreCard.h \
		src/scoreCard/scoreCardPerspectiveEditWidget.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\scoreCard\scoreCardPerspectiveEditWidget.h -o moc\moc_scoreCardPerspectiveEditWidget.cpp

moc/moc_lineEdit.cpp: src/common/edittLayoutInterface.h \
		src/common/widgetLayoutInterface.h \
		src/common/lineEdit.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\common\lineEdit.h -o moc\moc_lineEdit.cpp

moc/moc_edittLayoutInterface.cpp: src/common/widgetLayoutInterface.h \
		src/common/edittLayoutInterface.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\common\edittLayoutInterface.h -o moc\moc_edittLayoutInterface.cpp

moc/moc_editForm.cpp: src/common/comm.h \
		src/common/editRow.h \
		src/common/editForm.h
	D:\C++\Qt\4.8.5\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\common\editForm.h -o moc\moc_editForm.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: src/images.qrc \
		src/img/target.png \
		src/img/find.png \
		src/img/orgStruct.png \
		src/img/redo24_h.png \
		src/img/gear_32.png \
		src/img/star1_32.png
	d:\C++\Qt\4.8.5\bin\rcc.exe -name images src\images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 



####### Compile

obj/smartScoreWindow.o: src/smartScoreWindow/smartScoreWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\smartScoreWindow.o src\smartScoreWindow\smartScoreWindow.cpp

obj/centralWorkSpace.o: src/smartScoreWindow/centralWorkSpace.cpp src/orgStruct/orgStructWorkSpace.h \
		src/scoreCard/scoreCardWorkSpace.h \
		src/common/comm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\centralWorkSpace.o src\smartScoreWindow\centralWorkSpace.cpp

obj/orgStructWidget.o: src/orgStruct/orgStructWidget.cpp src/orgStruct/orgStruct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\orgStructWidget.o src\orgStruct\orgStructWidget.cpp

obj/orgStructEditWidget.o: src/orgStruct/orgStructEditWidget.cpp src/orgStruct/orgStruct.h \
		src/common/lineEdit.h \
		src/common/edittLayoutInterface.h \
		src/common/widgetLayoutInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\orgStructEditWidget.o src\orgStruct\orgStructEditWidget.cpp

obj/orgStructDb.o: src/orgStruct/orgStructDb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\orgStructDb.o src\orgStruct\orgStructDb.cpp

obj/orgStruct.o: src/orgStruct/orgStruct.cpp src/orgStruct/orgStructDb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\orgStruct.o src\orgStruct\orgStruct.cpp

obj/orgStructWorkSpace.o: src/orgStruct/orgStructWorkSpace.cpp src/orgStruct/orgStruct.h \
		src/orgStruct/orgStructWidget.h \
		src/common/comm.h \
		src/orgStruct/orgStructEditWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\orgStructWorkSpace.o src\orgStruct\orgStructWorkSpace.cpp

obj/scoreCard.o: src/scoreCard/scoreCard.cpp src/scoreCard/scoreCard.h \
		src/common/editRow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\scoreCard.o src\scoreCard\scoreCard.cpp

obj/scoreCardWorkSpace.o: src/scoreCard/scoreCardWorkSpace.cpp src/scoreCard/scoreCardWorkSpace.h \
		src/common/comm.h \
		src/orgStruct/orgStructWidget.h \
		src/orgStruct/orgStruct.h \
		src/scoreCard/scoreCardtTeeWidget.h \
		src/scoreCard/scoreCard.h \
		src/common/editRow.h \
		src/scoreCard/scoreCardPerspectiveEditWidget.h \
		src/common/editForm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\scoreCardWorkSpace.o src\scoreCard\scoreCardWorkSpace.cpp

obj/scoreCardtTeeWidget.o: src/scoreCard/scoreCardtTeeWidget.cpp src/scoreCard/scoreCardtTeeWidget.h \
		src/common/comm.h \
		src/scoreCard/scoreCard.h \
		src/common/editRow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\scoreCardtTeeWidget.o src\scoreCard\scoreCardtTeeWidget.cpp

obj/scoreCardPerspectiveEditWidget.o: src/scoreCard/scoreCardPerspectiveEditWidget.cpp src/scoreCard/scoreCardPerspectiveEditWidget.h \
		src/common/editForm.h \
		src/common/comm.h \
		src/common/editRow.h \
		src/scoreCard/scoreCard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\scoreCardPerspectiveEditWidget.o src\scoreCard\scoreCardPerspectiveEditWidget.cpp

obj/scoreCardDb.o: src/scoreCard/scoreCardDb.cpp src/scoreCard/scoreCardDb.h \
		src/scoreCard/scoreCard.h \
		src/common/editRow.h \
		src/common/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\scoreCardDb.o src\scoreCard\scoreCardDb.cpp

obj/lineEdit.o: src/common/lineEdit.cpp src/common/lineEdit.h \
		src/common/edittLayoutInterface.h \
		src/common/widgetLayoutInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\lineEdit.o src\common\lineEdit.cpp

obj/widgetLayoutInterface.o: src/common/widgetLayoutInterface.cpp src/common/widgetLayoutInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\widgetLayoutInterface.o src\common\widgetLayoutInterface.cpp

obj/edittLayoutInterface.o: src/common/edittLayoutInterface.cpp src/common/edittLayoutInterface.h \
		src/common/widgetLayoutInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\edittLayoutInterface.o src\common\edittLayoutInterface.cpp

obj/editForm.o: src/common/editForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\editForm.o src\common\editForm.cpp

obj/editRow.o: src/common/editRow.cpp src/common/editRow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\editRow.o src\common\editRow.cpp

obj/test.o: src/test/test.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\test.o src\test\test.cpp

obj/main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\main.o src\main.cpp

obj/moc_smartScoreWindow.o: moc/moc_smartScoreWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_smartScoreWindow.o moc\moc_smartScoreWindow.cpp

obj/moc_centralWorkSpace.o: moc/moc_centralWorkSpace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_centralWorkSpace.o moc\moc_centralWorkSpace.cpp

obj/moc_orgStructEditWidget.o: moc/moc_orgStructEditWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_orgStructEditWidget.o moc\moc_orgStructEditWidget.cpp

obj/moc_orgStructWidget.o: moc/moc_orgStructWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_orgStructWidget.o moc\moc_orgStructWidget.cpp

obj/moc_orgStructWorkSpace.o: moc/moc_orgStructWorkSpace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_orgStructWorkSpace.o moc\moc_orgStructWorkSpace.cpp

obj/moc_scoreCardWorkSpace.o: moc/moc_scoreCardWorkSpace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_scoreCardWorkSpace.o moc\moc_scoreCardWorkSpace.cpp

obj/moc_scoreCardtTeeWidget.o: moc/moc_scoreCardtTeeWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_scoreCardtTeeWidget.o moc\moc_scoreCardtTeeWidget.cpp

obj/moc_scoreCardPerspectiveEditWidget.o: moc/moc_scoreCardPerspectiveEditWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_scoreCardPerspectiveEditWidget.o moc\moc_scoreCardPerspectiveEditWidget.cpp

obj/moc_lineEdit.o: moc/moc_lineEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_lineEdit.o moc\moc_lineEdit.cpp

obj/moc_edittLayoutInterface.o: moc/moc_edittLayoutInterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_edittLayoutInterface.o moc\moc_edittLayoutInterface.cpp

obj/moc_editForm.o: moc/moc_editForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\moc_editForm.o moc\moc_editForm.cpp

obj/qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj\qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

